name: Password Manager CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 'Password Manager/requirements.txt'

    - name: Run tests
      run: |
        cd 'Password Manager'
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest tests/

    - name: Install linting and formatting dependencies
      run: |
        pip install flake8 black

    - name: Run linting
      run: |
        flake8 'Password Manager/app/' 'Password Manager/tests/'

    - name: Run code formatting
      run: |
        black --check 'Password Manager/app/' 'Password Manager/tests/'

    - name: Install static type checking dependencies
      run: |
        pip install mypy

    - name: Run static type checking
      run: |
        mypy 'Password Manager/app/' 'Password Manager/tests/'
    
    - name: Install security checking dependencies
      run: |
        pip install bandit

    - name: Run security checks
      run: |
        bandit -r 'Password Manager/app/'
